"""Head-to-head: published parameter-free screened hydrogenic model (Kregar / Di Rocco) vs this project's models,
all scored with the shared evaluate.py on the same 5847 NIST rows.

For parameter-free models (Kregar SHM, Slater, Clementi-Raimondi, Track A) the S1/S2/S3 columns are simply the
MAPE on the test rows (nothing is fitted).  For FITTED project models the S1/S2/S3 columns are the held-out numbers
after refitting on the training part, copied from docs/unified.md / results/model_comparison.md (they cannot be
recomputed from an all-data prediction file without leakage); the source is stated in the table.
Writes results/lit_comparison.{json,md}.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, ROOT)
import evaluate as EV  # noqa: E402

RES = os.path.join(ROOT, "results")
SPLITS = {"S1": lambda r: r["Z"] % 5 == 0, "S2": lambda r: r["Z"] >= 55, "S3": lambda r: r["N"] % 6 == 0}

# (label, file, n_params, kind)
MODELS = [
    ("Kregar/Di Rocco SHM, non-rel. (literature, this work's implementation)", "lit_kregar_nr_predictions.csv", 0, "free"),
    ("Kregar/Di Rocco SHM + Pauli corr. (literature)", "lit_kregar_pauli_predictions.csv", 0, "free"),
    ("Kregar/Di Rocco SHM + nl-avg Dirac (literature)", "lit_kregar_dirac_predictions.csv", 0, "free"),
    ("Slater 1930 rules, total-energy difference", "se_slater_total_predictions.csv", 0, "free"),
    ("Clementi-Raimondi 1963/67, total-energy difference", "se_cr_total_predictions.csv", 0, "free"),
    ("Track A zexp (exact O(Z^2,Z) + heuristic O(1) + rel/QED)", "fp_zexp_predictions.csv", 0, "free"),
    ("Project: pocket formula", "uni_pocket_predictions.csv", 8, "fitted"),
    ("Project: Track B GSHM final", "se_gshm_predictions.csv", 32, "fitted"),
    ("Project: u35 (exact sigma1 + fitted remainder)", "uni_u35_predictions.csv", 35, "fitted"),
    ("Project: pa_hier_rel (current final candidate)", "pa_hier_rel_predictions.csv", 33, "fitted"),
]
# Held-out (refit) MAPE for fitted models, from docs/unified.md section 1 table (2026-10-05).
HELDOUT = {
    "uni_pocket_predictions.csv": {"S1": 4.62, "S2": 11.3, "S3": 5.24},
    "se_gshm_predictions.csv": {"S1": 1.59, "S2": 170.0, "S3": 1.70},
    "uni_u35_predictions.csv": {"S1": 1.52, "S2": 57.2, "S3": 1.65},
    "pa_hier_rel_predictions.csv": {"S1": 1.91, "S2": 6.60, "S3": 2.00},
}
STRATA = ["ALL", "first_IE_neutral_atoms", "hydrogen_like", "N<=10", "11<=N<=36", "N>=37", "Z<=18", "19<=Z<=54",
          "Z>=55", "removed_l=s", "removed_l=p", "removed_l=d", "removed_l=f", "rearranged_config"]


def g(m, s, key="MAPE_%"):
    return m.get(s, {}).get(key)


def main():
    rows = []
    for label, fn, npar, kind in MODELS:
        path = os.path.join(RES, fn)
        if not os.path.exists(path):
            print("missing", fn)
            continue
        m = EV.evaluate(path)
        row = {"model": label, "file": fn, "n_params": npar, "kind": kind,
               "coverage": m["_coverage"]["predicted"],
               "median_APE_%": g(m, "ALL", "median_APE_%"),
               "frac_within_5%": g(m, "ALL", "frac_within_5%")}
        for s in STRATA:
            row[s] = g(m, s)
        for sp, f in SPLITS.items():
            if kind == "free":
                row[sp + "_test"] = g(EV.evaluate(path, subset=f), "ALL")
                row[sp + "_src"] = "test rows (no fit)"
            else:
                row[sp + "_test"] = HELDOUT[fn][sp]
                row[sp + "_src"] = "refit held-out, docs/unified.md"
        # S2 neutral first IE for the free models
        row["S2_neutral"] = g(EV.evaluate(path, subset=SPLITS["S2"]), "first_IE_neutral_atoms") if kind == "free" else None
        rows.append(row)
    with open(os.path.join(RES, "lit_comparison.json"), "w") as f:
        json.dump(rows, f, indent=1)

    def fmt(x):
        if x is None:
            return "-"
        return f"{x:.4f}" if x < 0.01 else (f"{x:.3g}" if x < 1000 else f"{x:.0f}")
    cols = ["n_params", "ALL", "median_APE_%", "first_IE_neutral_atoms", "hydrogen_like", "N<=10", "11<=N<=36",
            "N>=37", "Z>=55", "removed_l=d", "removed_l=f", "S1_test", "S2_test", "S3_test"]
    lines = ["| model | " + " | ".join(cols) + " |", "|" + "---|" * (len(cols) + 1)]
    for r in rows:
        lines.append("| " + r["model"] + " | " + " | ".join(
            str(r[c]) if c == "n_params" else fmt(r[c]) for c in cols) + " |")
    md = ("# Head-to-head: published screened hydrogenic model vs this project (MAPE %, 5847 NIST rows)\n\n"
          "Generated by models/literature/compare.py. S1/S2/S3 for parameter-free models = MAPE on the test rows; "
          "for fitted project models = refit held-out values quoted from docs/unified.md.\n\n" + "\n".join(lines) + "\n")
    with open(os.path.join(RES, "lit_comparison.md"), "w", encoding="utf-8") as f:
        f.write(md)
    print(md)


if __name__ == "__main__":
    main()
