"""Generate docs/cheat_sheet_pa_bound9.md (one-page cheat sheet) from results/pa_params.json and
results/audit_components.json. Every number is read from those files; none is typed.

    py -3.11 tools/audit_components.py && py -3.11 tools/cheat_sheet_bound9.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    c = json.load(open(os.path.join(ROOT, "results", "pa_params.json"), encoding="utf-8"))["candidates"]["pa_bound9"]
    P = dict(zip(c["names"], c["values"]))
    na = next(r for r in json.load(open(os.path.join(ROOT, "results", "audit_components.json"), encoding="utf-8"))
              if r["Z"] == 11 and r["model"] == "pa_bound9")
    nu = na["nu_groups"]
    md = f"""# Cheat sheet: bounded 9-parameter variant (pa_bound9)

*Generated by `tools/cheat_sheet_bound9.py` from `results/pa_params.json` and `results/audit_components.json`.
This is **not** the 8-parameter "pocket formula" (paper Appendix A). pa_bound9 uses the same five electron groups,
but it has exact σ₁ and a bounded remainder.*

## Equation (energies in eV, Ry = 13.605693 eV)

    IE   = mu(Z) * [ Ry * Zeff^2 / n^2 * F_nj(Zeff)  +  Ry * x_l * K_l(k) / n^2 ]  -  QED/FNS * (Zeff/Z)^2
    Zeff = Z - sigma1 - D
    D    = T / (Za + kappa + |T|/h),   T = sum_g tau_g * nu_g,   Za = Z - N + 1
    h    = (N - 1) - sigma1   if T >= 0,   else sigma1

The bound Za ≤ Zeff ≤ Z holds for any parameter values. F_nj is the Dirac/Schrödinger ratio for charge Zeff, with j
from jj filling. There is no relativistic bracket in this variant (R = 1). QED/FNS applies only to 1s and 2s removal.

## Parameters (all-data fit)

| τ_same | τ_in | τ_core | τ_df | τ_out | κ (used = abs + 0.05) | x_p | x_d | x_f |
|---|---|---|---|---|---|---|---|---|
| {P['tau_same']:.4f} | {P['tau_in']:.4f} | {P['tau_core']:.4f} | {P['tau_df']:.4f} | {P['tau_out']:.4f} | {P['kappa']:.4f} ({abs(P['kappa']) + 0.05:.4f}) | {P['x_p']:.4f} | {P['x_d']:.4f} | {P['x_f']:.4f} |

## Grouping rule (removed electron in subshell (n, l))

- **same**: the other electrons of (n, l).
- **out**: n′ > n, or n′ = n with l′ > l.
- **s or p target**:
  - **in**: n′ ≥ n − 1 (the same-n s electrons of a p target, plus the whole (n − 1) shell, *including its d and f
    electrons*);
  - **core**: n′ ≤ n − 2.
- **d or f target**: every inner electron is **df**. τ_df applies only to d or f targets. For Fe 4s, the 3d⁶
  electrons are in **in**: (ν_same, ν_in, ν_core, ν_df, ν_out) = (1, 14, 10, 0, 0).
- **Hund kink K_l(k)**:
  - K_p = 0, 0.6, 1.2, −1.2, −0.6, 0 for k = 1…6;
  - K_d = (5/9)(0, 1, 2, 3, 4, −4, −3, −2, −1, 0);
  - K_s = 0.

## Inputs you cannot derive by hand

σ₁ (exact first-order screening, frozen configuration), μ(Z) and QED/FNS are tabulated per row in
`results/model_inputs.csv`. `tools/verify_from_inputs.py` reproduces the code from that table to 7·10⁻¹⁶.

## Worked example: Na I, 3s removed (Z = 11, N = 11)

| step | value |
|---|---|
| σ₁ (model_inputs.csv) | {na['sigma1']:.5f} |
| ν_g (same, in, core, df, out) | {', '.join(str(int(nu[g])) for g in ['same', 'in', 'core', 'df', 'out'])} |
| T = τ_in·8 + τ_core·2 | {na['T']:.5f} |
| h = (N − 1) − σ₁ | {na['h']:.5f} |
| denominator Za + κ + T/h | {na['denominator']:.5f} |
| D | {na['D_rem']:.5f} |
| Zeff = 11 − σ₁ − D | {na['Zeff']:.5f} |
| Ry Zeff²/9 | {na['rydberg_term']:.5f} eV |
| × F_nj = {na['F_Dirac']:.8f}, × μ = {na['mu']:.9f} | |
| Hund term (s) | 0 |
| **IE** | **{na['IE']:.4f} eV** (NIST {na['IE_NIST']:.4f}, {na['err_pct']:+.2f} %) |

## Honest limits (paper Table 6, all-data fit)

- Ca I is predicted 29 % too low and Fe I 7.6 % too low.
- Neutral first IEs average 12.0 % error.
- No s-electron correction term exists in this variant; do not add one by hand.
"""
    out = os.path.join(ROOT, "docs", "cheat_sheet_pa_bound9.md")
    open(out, "w", encoding="utf-8").write(md)
    print("wrote", out)


if __name__ == "__main__":
    main()
