"""Same-row comparison: final (33 p), pa_bound9 (9 p), Mendoza et al. 2011, on the rows Mendoza covers.

    py -3.11 tools/compare_mendoza.py   -> results/compare_mendoza.md / .json
"""
import csv
import json
import os

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = os.path.join(ROOT, "results")
MODELS = [("Screened Rydberg, final (33 p)", "pa_hier_rel_predictions.csv"),
          ("bounded 9-parameter (pa_bound9)", "pa_bound9_predictions.csv"),
          ("Mendoza et al. 2011", "bench_mendoza2011_predictions.csv")]


def load(fn):
    out = {}
    for r in csv.DictReader(open(os.path.join(R, fn), encoding="utf-8")):
        try:
            v = float(r["IE_pred_eV"])
        except (ValueError, TypeError):
            continue
        if np.isfinite(v):
            out[(int(r["Z"]), int(r["N"]))] = v
    return out


def main():
    ref = {}
    for r in csv.DictReader(open(os.path.join(ROOT, "data", "nist_ie.csv"), encoding="utf-8")):
        ref[(int(r["Z"]), int(r["N"]))] = (float(r["IE_eV"]), r.get("status", ""))
    preds = [load(fn) for _, fn in MODELS]
    rows = sorted(set(ref) & set(preds[0]) & set(preds[1]) & set(preds[2]))
    Z = np.array([k[0] for k in rows]); N = np.array([k[1] for k in rows])
    y = np.array([ref[k][0] for k in rows]); st = np.array([ref[k][1] for k in rows])
    strata = [("all covered rows", np.ones(len(rows), bool)), ("ions only (Z > N)", Z > N),
              ("charge ≥ 3", Z - N >= 3), ("singly charged (Z − N = 1)", Z - N == 1),
              ("neutral atoms", Z == N), ("N ≤ 10", N <= 10), ("11 ≤ N ≤ 36", (N >= 11) & (N <= 36)),
              ("N ≥ 37", N >= 37), ("H-like", N == 1), ("Z ≥ 55", Z >= 55),
              ("experimental", np.char.startswith(st.astype(str), "exp"))]
    apes = [np.abs(np.array([p[k] for k in rows]) - y) / y * 100 for p in preds]
    res = {"n_rows": len(rows), "strata": {}}
    L = [f"# Same-row comparison on the {len(rows)} rows Mendoza et al. 2011 covers", "",
         "Generated by `tools/compare_mendoza.py` from the prediction CSVs; all-data fits of the project models "
         "(in-sample, like Mendoza's own fit to NIST+FAC data). Cells: mean APE % / median APE % [n].", "",
         "| stratum | " + " | ".join(m for m, _ in MODELS) + " |", "|---|---|---|---|"]
    for name, m in strata:
        cells, d = [], {}
        for (mn, _), a in zip(MODELS, apes):
            if m.sum():
                d[mn] = {"n": int(m.sum()), "mean": float(a[m].mean()), "median": float(np.median(a[m]))}
                cells.append(f"{a[m].mean():.3g} / {np.median(a[m]):.3g} [{int(m.sum())}]")
        res["strata"][name] = d
        L.append(f"| {name} | " + " | ".join(cells) + " |")
    L += ["", "| distribution (all covered rows) | " + " | ".join(m for m, _ in MODELS) + " |", "|---|---|---|---|"]
    for q, lab in ((90, "p90 APE %"), (99, "p99 APE %")):
        L.append(f"| {lab} | " + " | ".join(f"{np.percentile(a, q):.3g}" for a in apes) + " |")
    L.append("| max APE % | " + " | ".join(f"{a.max():.3g}" for a in apes) + " |")
    for t in (1, 5, 10):
        L.append(f"| rows within {t} % | " + " | ".join(f"{(a <= t).mean() * 100:.1f} %" for a in apes) + " |")
    w = [np.mean(apes[0] < apes[2]), np.mean(apes[1] < apes[2])]
    L += ["", f"Row-by-row: the final model is closer to NIST than Mendoza on {w[0] * 100:.1f} % of the rows; "
          f"pa_bound9 on {w[1] * 100:.1f} %."]
    c = json.load(open(os.path.join(ROOT, "models", "benchmarks", "mendoza2011", "constants.json"), encoding="utf-8"))
    vals = [v for row in c["sigma"].values() for v in row.values()]
    nz = sum(1 for v in vals if v != 0)
    L += ["", f"Mendoza constants: a {len(c['sigma'])}×{len(c['sigma'])} matrix, {len(vals)} entries, "
          f"{nz} non-zero. These are published constants fitted by the authors, counted as published numbers, not as "
          f"independent degrees of freedom. They are the only model-specific numbers our implementation of their "
          f"IE prescription uses (plus the fine-structure constant). The project models have 33 and 9 global fitted "
          f"parameters."]
    res.update(row_wins={"final_vs_mendoza": w[0], "bound9_vs_mendoza": w[1]}, mendoza_nonzero_constants=nz)
    open(os.path.join(R, "compare_mendoza.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    json.dump(res, open(os.path.join(R, "compare_mendoza.json"), "w", encoding="utf-8"), indent=1)
    print("\n".join(L))


if __name__ == "__main__":
    main()
