"""One-off: remove code/file references from docs/paper_draft.md (journal text should not cite file paths)."""
import io, re
P = "docs/paper_draft.md"
s = io.open(P, encoding="utf-8").read()

def rx(lit):  # literal text, any whitespace run may be a line wrap
    return r"\s+".join(re.escape(w) for w in lit.split())

R = [
 ("The final model (code name pa_hier_rel) is", "The final model is"),
 ("The bounded 9-parameter variant (pa_bound9) and the pocket formula", "The bounded 9-parameter variant and the pocket formula"),
 (" (`tools/check_grouping_rule.py`)", ""),
 ("every per-row input in `results/model_inputs.csv`:", "every per-row input as a table in the repository:"),
 ("(`tools/verify_from_inputs.py`, which imports no model code)", "(it imports no model code)"),
 ("for the final model and for pa_bound9.", "for the final model and for the bounded 9-parameter variant."),
 (" and `results/uni_final_params.json`;", ";"),
 ("pa_bound9 uses the pocket formula's five", "The bounded 9-parameter variant uses the pocket formula's five"),
 (" (`data/nist_ie.csv`)", ""),
 (" (evaluate.py, `status=` strata)", ""),
 (" (`evaluate.py`)", ""),
 ("pa_hier_rel 1.844", "the final model 1.844"),
 ("lowest-scoring Push B candidate", "lowest-scoring candidate of a second, independent search"),
 (" (`docs/preregistration_v2.md`, `models/v2/NOTES.md`)", ""),
 (" (sha256, `models/v2/PREREG_HASH.txt`)", " (sha256)"),
 ("committed to git afterwards", "committed to the repository afterwards"),
 ("; `docs/review/reproducibility_py311.md`)", ")"),
 ("The u29 V1 fit", "The V1 fit of the 29-parameter linear-remainder variant"),
 ("and u35's blind S2 moves", "and the blind S2 of the 35-parameter linear-remainder model moves"),
 ("cell, `results/benchmark_matrix.md` (`tools/benchmark_matrix.py`),", "cell,"),
 (" Sources: `results/model_comparison.md`, `results/uni_validation.md`.", ""),
 ("pa_bound9 (2.90 %)", "the 9-parameter variant (2.90 %)"),
 (" (ratios from `results/benchmark_matrix.md`)", ""),
 ("pb_clip_pos (30 parameters)", "the best candidate of the second search (30 parameters)"),
 ("the 28-parameter hierarchical variant pa_hier at 2.37", "the 28-parameter hierarchical variant at 2.37"),
 ("1.48 % for u35 and", "1.48 % for the linear-remainder model and"),
 (" (source: `results/lit_comparison.md` / `docs/literature.md` §2.2)", ""),
 ("(pb_exp_pos, 3.73)", "(3.73)"),
 ("u35 57.233 %", "linear-remainder model 57.233 %"),
 (" for every fitted candidate in `results/model_comparison.csv`", " for every fitted candidate"),
 (" (`results/known_failures.json`, refit on Z ≤ 54)", " (refit on Z ≤ 54)"),
 ("fitted (`results/known_failures.json`) the", "fitted the"),
 (" (`docs/first_principles.md` §2.1)", ""),
 (" (`results/lit_comparison.md`)", ""),
 (" (`models/benchmarks/mendoza2011/`)", ""),
 (" Source: `tools/compare_mendoza.py` → `results/compare_mendoza.md`.", ""),
 ("the full table for N = 1–110 is in `results/fp_zexp_coefficients.csv`, with values for all 5847 rows in `results/fp_zexp_rows_coefficients.csv`.",
  "the full table for N = 1–110, with values for all 5847 rows, is in the repository."),
 ("Printed by `tools/audit_components.py` and `tools/case_study_table.py` (`results/case_studies.md`); the script asserts that",
  "Generated by a script that asserts that"),
 ("(R = 1 for pa_bound9)", "(R = 1 for the 9-parameter variant)"),
 ("and Pb, pa_bound9 only on Na", "and Pb, the 9-parameter variant only on Na"),
 ("(6.4 % for u35)", "(6.4 % for the linear-remainder model)"),
 ("(Table 6; `results/audit_components.md`)", "(Table 6)"),
 ("The bounded 9-parameter variant pa_bound9 (selection", "The bounded 9-parameter variant (selection"),
 ("**Table A1.** Source: `results/uni_final_params.json`, which is identical to `results/pa_params.json`.", "**Table A1.** Fitted values of the final model (all-data fit)."),
 ("**Bounded 9-parameter variant, pa_bound9 (all-data fit, `results/pa_params.json`, candidate `pa_bound9`).**", "**Bounded 9-parameter variant (all-data fit).**"),
 (" (`tools/hand_recompute.py`)", ""),
 (" (Verified by `tools/check_grouping_rule.py`.)", ""),
 ("(8 parameters, all-data fit, `results/uni_params.json`)", "(8 parameters, all-data fit)"),
 (" (docs/semi_empirical.md)", ""),
 # table cells
 ("(final; code name pa_hier_rel)", "(final)"),
 (" (pa_bound9)", ""),
 (" (uni_pocket)", ""),
 (' ("zexp")', ""), (' ("u35")', ""),
 ('Screened Rydberg formula (final, "pa_hier_rel")', "Screened Rydberg formula (final)"),
 ("| u35 (35 p) |", "| linear remainder (35 p) |"),
 ("| u35 | exact σ₁ as", "| linear remainder (35 p) | exact σ₁ as"),
 ("| pa_bound9 |", "| 9-parameter |"),
]
for old, new in R:
    pat = re.compile(rx(old))
    n = len(pat.findall(s))
    assert n >= 1, ("not found", old)
    s = pat.sub(lambda m: new, s)

# figures sentence
m = re.search(r"Further figures are in the repository:.*?residuals \(`results/figures/uni_residuals\.png`\)\.\n\n", s, re.S)
assert m; s = s.replace(m.group(0), "")
# data availability
i = s.index("All code, data and results are in the project repository,")
j = s.index("## AI-assistance disclosure")
s = s[:i] + ("All code, data and results are in the project repository, https://github.com/AwaisSDev/screened-rydberg-formula, "
 "archived on Zenodo as version 1.0.0 (doi:10.5281/zenodo.23211017). It contains the NIST table and the shared scorer; "
 "the exact first-order coefficients for every configuration; the final model with its fitted parameters and the "
 "predictions for all rows; the validation scripts; the re-implementations of the two published models; every per-row "
 "model input with the stand-alone reference implementation, which reproduces the model's predictions to 7·10⁻¹⁶; the "
 "component audit and the benchmark matrix with row counts in every cell; and a command-line and Python interface that "
 "evaluates the formula for any Z ≤ 118 and N ≤ Z. The README describes each file.\n\n") + s[j:]
io.open(P, "w", encoding="utf-8", newline="\n").write(s)
body = s[:s.index("## References")]
left = re.findall(r"`[^`]*`|\b\w+_\w+\.(?:py|csv|json|md|png)\b|\b(?:results|tools|models|docs)/\S+|pa_hier|pa_bound|uni_|\bu35\b|\bu29\b|pb_|zexp|Push [AB]", body)
print("remaining:", left)
